services:
  # Backend for GitHub Codespaces
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: coaching_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///./data/coaching_site.db
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-dev-secret-key}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin123}
      - ENVIRONMENT=development
    command: ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  # Frontend for local development
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: coaching_frontend_dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_SITE_URL=http://localhost:3000
    command: ["npm", "run", "dev"]

volumes:
  backend_data:
    driver: local